package runners;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;

@CucumberOptions(
        features = "@target/rerun.txt",   // rerun file generated by TestNGRunner
        glue = {"stepdefinitions"},
        plugin = {
                "pretty",
                "html:target/cucumber-reports-rerun.html"
        }
)
public class FailedRunner extends AbstractTestNGCucumberTests {
}
